#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Jun 02, 2021 06:49:55 PM UTC  platform: Linux

import sys
import CambiarEspecialistaDePaciente
from Plataforma import Plataforma


try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root, mPlataforma
    mPlataforma = Plataforma()
    w = gui
    top_level = top
    root = top
    generarTabla()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def obtenerListaUsuarios():
    listaUsuarios = mPlataforma.verUsuariosPacientes()
    return listaUsuarios

def generarTabla():
    w.Label1 = tk.Label(w.Canvas1, width=3, text='id', borderwidth=2, relief='ridge')
    w.Label1.grid(row=0, column=0)

    w.Label2 = tk.Label(w.Canvas1, width=20, text='Nombre', borderwidth=2, relief='ridge')
    w.Label2.grid(row=0, column=1)

    w.Label3 = tk.Label(w.Canvas1, width=40, text='Apellidos', borderwidth=2, relief='ridge')
    w.Label3.grid(row=0, column=2)


    w.Label5 = tk.Label(w.Canvas1, width=13, text='idEspecialista', borderwidth=2, relief='ridge')
    w.Label5.grid(row=0, column=3)

    w.Label6 = tk.Label(w.Canvas1, width=20, text='Nombre', borderwidth=2, relief='ridge')
    w.Label6.grid(row=0, column=4)

    w.Label7 = tk.Label(w.Canvas1, width=40, text='Apellidos', borderwidth=2, relief='ridge')
    w.Label7.grid(row=0, column=5)

    w.Label8 = tk.Label(w.Canvas1, width=5, text='Mod.', borderwidth=2, relief='ridge')
    w.Label8.grid(row=0, column=6)


    listaUsuarios = obtenerListaUsuarios()
    if listaUsuarios==99:
        tk.LabelDinamico = tk.Label(top_level,width = 70, text="Error en la conexión con la BD. Consulte conexión a Internet")
        tk.LabelDinamico.grid(row=1, column=0)

    else:
        for i in range(0,len(listaUsuarios)):
            tk.LabelDinamico = tk.Label(w.Canvas1, width=3, text=listaUsuarios[i][0], borderwidth=2, relief='ridge')
            tk.LabelDinamico.grid(row=i+1,column=0)

            tk.LabelDinamico = tk.Label(w.Canvas1, width=20, text=listaUsuarios[i][3], borderwidth=2, relief='ridge')
            tk.LabelDinamico.grid(row=i + 1, column=1)

            tk.LabelDinamico = tk.Label(w.Canvas1, width=40, text=listaUsuarios[i][6], borderwidth=2, relief='ridge')
            tk.LabelDinamico.grid(row=i + 1, column=2)

            tk.LabelDinamico = tk.Label(w.Canvas1, width=13, text=listaUsuarios[i][1], borderwidth=2, relief='ridge')
            tk.LabelDinamico.grid(row=i + 1, column=3)

            tk.LabelDinamico = tk.Label(w.Canvas1, width=20, text=listaUsuarios[i][9], borderwidth=2, relief='ridge')
            tk.LabelDinamico.grid(row=i + 1, column=4)

            tk.LabelDinamico = tk.Label(w.Canvas1, width=40, text=listaUsuarios[i][12], borderwidth=2, relief='ridge')
            tk.LabelDinamico.grid(row=i + 1, column=5)

            tk.BotonDinamico = tk.Button(w.Canvas1, text='C', command=lambda i=i : comandoModificar(listaUsuarios[i][0]))
            tk.BotonDinamico.grid(row=i+1, column=6)


def comandoModificar(pIdUsuarioPaciente):
    a = CambiarEspecialistaDePaciente.vp_start_gui(pIdUsuarioPaciente)
    for widget in w.Canvas1.winfo_children():
        widget.destroy()
    generarTabla()

if __name__ == '__main__':
    import AdministrarUsuariosPaciente
    AdministrarUsuariosPaciente.vp_start_gui()




