#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Jun 02, 2021 06:49:55 PM UTC  platform: Linux

import sys
from Plataforma import Plataforma
import BorrarTipoAnalisis
import ModificarTipoAnalisis

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root, mPlataforma
    mPlataforma = Plataforma()
    w = gui
    top_level = top
    root = top
    generarTabla()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def obtenerListaUsuarios():
    listaUsuarios = mPlataforma.verTiposAnalisis()
    return listaUsuarios

def generarTabla():
    w.Label1 = tk.Label(w.Canvas1, width=3, text='id', borderwidth=2, relief='ridge')
    w.Label1.grid(row=0, column=0)

    w.Label2 = tk.Label(w.Canvas1, width=20, text='Nombre', borderwidth=2, relief='ridge')
    w.Label2.grid(row=0, column=1)

    w.Label3 = tk.Label(w.Canvas1, width=60, text='Descripción', borderwidth=2, relief='ridge')
    w.Label3.grid(row=0, column=2)

    w.Label4 = tk.Label(w.Canvas1, width=5, text='Mod.', borderwidth=2, relief='ridge')
    w.Label4.grid(row=0, column=3)

    w.Label5 = tk.Label(w.Canvas1, width=5, text='Borrar', borderwidth=2, relief='ridge')
    w.Label5.grid(row=0, column=4)

    listaUsuarios = obtenerListaUsuarios()
    if listaUsuarios==99:
        tk.LabelDinamico = tk.Label(top_level,width = 70, text="Error en la conexión con la BD. Consulte conexión a Internet")
        tk.LabelDinamico.grid(row=1, column=0)

    else:
        for i in range(0,len(listaUsuarios)):
            tk.LabelDinamico = tk.Label(w.Canvas1, width=3, text=listaUsuarios[i][0], borderwidth=2, relief='ridge')
            tk.LabelDinamico.grid(row=i+1,column=0)

            tk.LabelDinamico = tk.Label(w.Canvas1, width=20, text=listaUsuarios[i][1], borderwidth=2, relief='ridge')
            tk.LabelDinamico.grid(row=i + 1, column=1)

            tk.LabelDinamico = tk.Label(w.Canvas1, width=60, text=listaUsuarios[i][2], borderwidth=2, relief='ridge')
            tk.LabelDinamico.grid(row=i + 1, column=2)

            tk.BotonDinamico = tk.Button(w.Canvas1, text='M', command=lambda i=i : comandoModificar(listaUsuarios[i][0]))
            tk.BotonDinamico.grid(row=i+1, column=3)

            tk.BotonDinamico = tk.Button(w.Canvas1, text='B', command=lambda i=i : comandoBorrar(listaUsuarios[i][0]))
            tk.BotonDinamico.grid(row=i+1, column=4)

def comandoBorrar(pIdTipoAnalisis):
    a = BorrarTipoAnalisis.vp_start_gui(pIdTipoAnalisis)
    for widget in w.Canvas1.winfo_children():
        widget.destroy()
    generarTabla()

def comandoModificar(pIdTipoAnalisis):
    a = ModificarTipoAnalisis.vp_start_gui(pIdTipoAnalisis)
    for widget in w.Canvas1.winfo_children():
        widget.destroy()
    generarTabla()

if __name__ == '__main__':
    import AdministrarTiposAnalisis
    AdministrarTiposAnalisis.vp_start_gui()




