#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Jun 01, 2021 01:27:24 PM UTC  platform: Linux

import sys
from Plataforma import Plataforma
mPlataforma = Plataforma()
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window(p1):
    print('AnadirTipoAnalisis_support.destroy_window')
    sys.stdout.flush()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def ejecutar_Aceptar(a1, a2):
    a = top_level
    algunoVacio = False
    tk.Label3 = tk.Label(a)
    tk.Label3.place(relx=0.21, rely=0.658, height=21, width=429)
    tk.Label3.configure(activebackground="#f9f9f9")
    tk.Label3.configure(anchor='w')

    if a1 == '' :
        w.Label1.configure(foreground="red")
        algunoVacio=True
    else:
        w.Label1.configure(foreground="black")
    if a2 == '' :
        w.Label2.configure(foreground="red")
        algunoVacio == True
    else:
        w.Label2.configure(foreground="black")

    if algunoVacio == True:
        tk.Label3.configure(text='''Algún campo está vacío. Por favor rellénelo''')
    else:
        resultadoSQL = mPlataforma.anadirTipoAnalisis(a1, a2)
        if resultadoSQL == 99:
            tk.Label3.configure(text='''Error al añadir tipo de analisis. Revise la conexión a Internet''')
        else:
            tk.Label3.configure(text='''Tipo de Análisis creado correctamente''')
            w.TEntry1.delete(0,'end')
            w.TEntry2.delete(0, 'end')






if __name__ == '__main__':
    import AnadirTipoAnalisis
    AnadirTipoAnalisis.vp_start_gui()




