#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Jun 01, 2021 01:27:24 PM UTC  platform: Linux

import sys
from Plataforma import Plataforma
mPlataforma = Plataforma()
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window(p1):
    print('AnadirUsuarioEspecialista_support.destroy_window')
    sys.stdout.flush()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def ejecutar_Aceptar(a1, a2, a3, a4):
    a = top_level
    algunoVacio = False
    tk.Label5 = tk.Label(a)
    tk.Label5.place(relx=0.21, rely=0.658, height=21, width=429)
    tk.Label5.configure(activebackground="#f9f9f9")
    tk.Label5.configure(anchor='w')

    if a1 == '' :
        w.Label1.configure(foreground="red")
        algunoVacio=True
    else:
        w.Label1.configure(foreground="black")
    if a2 == '' :
        w.Label2.configure(foreground="red")
        algunoVacio == True
    else:
        w.Label2.configure(foreground="black")
    if a3 == '' :
        w.Label3.configure(foreground="red")
        algunoVacio = True
    else:
        w.Label3.configure(foreground="black")
    if a4 == '' :
        w.Label4.configure(foreground="red")
        algunoVacio = True
    else:
        w.Label4.configure(foreground="black")

    if algunoVacio == True:
        tk.Label5.configure(text='''Algún campo está vacío. Por favor rellénelo''')
    else:
        resultadoSQL = mPlataforma.anadirUsuarioEspecialista(a1, a2, a3, a4)
        if resultadoSQL == 99:
            tk.Label5.configure(text='''Error al añadir usuario. Revise que el Email no esté repetido y la conexión a Internet''')
        else:
            tk.Label5.configure(text='''Usuario creado correctamente''')
            w.TEntry1.delete(0, 'end')
            w.TEntry2.delete(0, 'end')
            w.TEntry3.delete(0,'end')
            w.TEntry4.delete(0, 'end')







if __name__ == '__main__':
    import AnadirUsuarioEspecialista
    AnadirUsuarioEspecialista.vp_start_gui()




