#############################################################################
# Generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#  Jun 01, 2021 01:27:08 PM UTC  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x450+508+105
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1351 738
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    frame $top.fra45 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 365 -highlightcolor black -width 455 
    vTcl:DefineAlias "$top.fra45" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra45
    ttk::entry $site_3_0.tEn49 \
        -foreground {} -background {} -takefocus {} -cursor fleur 
    vTcl:DefineAlias "$site_3_0.tEn49" "TEntry1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab50 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text Nombre 
    vTcl:DefineAlias "$site_3_0.lab50" "Nombre" vTcl:WidgetProc "Toplevel1" 1
    ttk::entry $site_3_0.tEn51 \
        -foreground {} -background {} -takefocus {} -cursor xterm 
    vTcl:DefineAlias "$site_3_0.tEn51" "TEntry2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab53 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text Apellidos 
    vTcl:DefineAlias "$site_3_0.lab53" "Label1" vTcl:WidgetProc "Toplevel1" 1
    ttk::entry $site_3_0.tEn54 \
        -foreground {} -background {} -takefocus {} -cursor xterm 
    vTcl:DefineAlias "$site_3_0.tEn54" "TEntry3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab55 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text eMail 
    vTcl:DefineAlias "$site_3_0.lab55" "Label2" vTcl:WidgetProc "Toplevel1" 1
    ttk::entry $site_3_0.tEn56 \
        -foreground {} -background {} -takefocus {} -cursor xterm 
    vTcl:DefineAlias "$site_3_0.tEn56" "TEntry4" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab57 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text contraseña 
    vTcl:DefineAlias "$site_3_0.lab57" "Label3" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but59 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 \
        -command Plataforma.anadirUsuario() -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text Aceptar 
    vTcl:DefineAlias "$site_3_0.but59" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but60 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 \
        -command destroy_window() -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text Cancelar 
    vTcl:DefineAlias "$site_3_0.but60" "Button2" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.tEn49 \
        -in $site_3_0 -x 0 -relx 0.505 -y 0 -rely 0.329 -width 204 \
        -relwidth 0 -height 21 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab50 \
        -in $site_3_0 -x 0 -relx 0.11 -y 0 -rely 0.329 -width 0 \
        -relwidth 0.152 -height 0 -relheight 0.058 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tEn51 \
        -in $site_3_0 -x 0 -relx 0.505 -y 0 -rely 0.411 -width 204 \
        -relwidth 0 -height 21 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab53 \
        -in $site_3_0 -x 0 -relx 0.11 -y 0 -rely 0.411 -width 0 \
        -relwidth 0.152 -height 0 -relheight 0.058 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tEn54 \
        -in $site_3_0 -x 0 -relx 0.505 -y 0 -rely 0.493 -width 204 \
        -relwidth 0 -height 21 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab55 \
        -in $site_3_0 -x 0 -relx 0.11 -y 0 -rely 0.493 -width 0 \
        -relwidth 0.108 -height 0 -relheight 0.058 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tEn56 \
        -in $site_3_0 -x 0 -relx 0.505 -y 0 -rely 0.575 -width 204 \
        -relwidth 0 -height 21 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab57 \
        -in $site_3_0 -x 0 -relx 0.11 -y 0 -rely 0.575 -width 0 \
        -relwidth 0.218 -height 0 -relheight 0.058 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but59 \
        -in $site_3_0 -x 0 -relx 0.747 -y 0 -rely 0.877 -width 73 -relwidth 0 \
        -height 33 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but60 \
        -in $site_3_0 -x 0 -relx 0.527 -y 0 -rely 0.877 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra45 \
        -in $top -x 0 -relx 0.117 -y 0 -rely 0.089 -width 0 -relwidth 0.758 \
        -height 0 -relheight 0.811 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}



set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

