#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Jun 06, 2021 07:55:57 PM UTC  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import BorrarTipoAnalisis_support

def vp_start_gui(pIdTipoAnalisis):
    '''Starting point when module is the main routine.'''
    global val, w, root, idTipoAnalisis
    root = tk.Tk()
    top = Toplevel1 (root)
    idTipoAnalisis = pIdTipoAnalisis
    BorrarTipoAnalisis_support.init(root, top, idTipoAnalisis)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    BorrarTipoAnalisis_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("436x226+413+259")
        top.minsize(1, 1)
        top.maxsize(1351, 738)
        top.resizable(1,  1)
        top.title("New Toplevel")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.032, rely=0.487, height=20, width=415)
        self.Label1.configure(text='''¿Está seguro de que desea borrar este Tipo de Análisis?''')

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.229, rely=0.664, height=33, width=73)
        self.Button1.configure(borderwidth="2")
        self.Button1.configure(command=lambda:BorrarTipoAnalisis_support.destroy_window())
        self.Button1.configure(text='''No''')

        self.Button2 = tk.Button(top)
        self.Button2.place(relx=0.596, rely=0.664, height=33, width=73)
        self.Button2.configure(borderwidth="2")
        self.Button2.configure(text='''Sí''')
        self.Button2.configure(command=lambda:BorrarTipoAnalisis_support.borrar(idTipoAnalisis))

if __name__ == '__main__':
    vp_start_gui()
