#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Jun 07, 2021 03:27:57 PM UTC  platform: Linux

import sys
from Plataforma import Plataforma
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import CambiarEspecialistaDePaciente_support


def vp_start_gui(pIdPaciente):
    '''Starting point when module is the main routine.'''
    global val, w, root, idPaciente, mPlataforma
    mPlataforma = Plataforma()
    idPaciente = pIdPaciente
    root = tk.Tk()
    top = Toplevel1 (root)
    CambiarEspecialistaDePaciente_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    CambiarEspecialistaDePaciente_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("500x350+383+106")
        top.minsize(1, 1)
        top.maxsize(1351, 738)
        top.resizable(1,  1)
        top.title("New Toplevel")

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.617, rely=0.867, height=33, width=73)
        self.Button1.configure(borderwidth="2")
        self.Button1.configure(text='''Cancelar''')
        self.Button1.configure(command = lambda:CambiarEspecialistaDePaciente_support.destroy_window())

        self.Button2 = tk.Button(top)
        self.Button2.place(relx=0.8, rely=0.867, height=33, width=73)
        self.Button2.configure(borderwidth="2")
        self.Button2.configure(text='''Aceptar''')
        self.Button2.configure(command=lambda:CambiarEspecialistaDePaciente_support.cambiarEspecialistaDePaciente(idPaciente, str(self.ComboBox.get()).split(' ')[0]))

        self.Label1 = tk.Label(top, width=40, text='Selecciona especialista', borderwidth=2, relief='ridge')
        self.Label1.place(relx=0.4, rely=0.567, height=23, width=273)
        self.ComboBox = ttk.Combobox(top)
        self.ComboBox.place(relx=0.4, rely=0.667, height=23, width=273)


        listaUsuarios = mPlataforma.verUsuariosEspecialistas()
        listaUsuariosFiltrada = []
        for i in range(len(listaUsuarios)):
            listaUsuariosFiltrada.append((str(listaUsuarios[i][0]) + ' ' + str(listaUsuarios[i][1]) + ' ' + str(listaUsuarios[i][4])))
        print(listaUsuariosFiltrada)
        self.ComboBox["values"] = listaUsuariosFiltrada



if __name__ == '__main__':
    vp_start_gui()





