#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Jun 01, 2021 01:27:24 PM UTC  platform: Linux

import sys
from Plataforma import Plataforma
mPlataforma = Plataforma()
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window(p1):
    print('ModificarUsuarioEspecialista_support.destroy_window')
    sys.stdout.flush()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def ejecutar_Aceptar(pIdUsuarioEspecialista, a1, a2, a3, a4):
    resultadoSQL = mPlataforma.modificarUsuario(pIdUsuarioEspecialista,str(a1), str(a2), str(a3), str(a4))
    if resultadoSQL == 99:
        tk.Label5.configure(text='''Error al modificar tipo de analisis. Revise la conexión a Internet''')
    else:
        tk.Label5.configure(text='''Modificado correctamente''')
        top_level.quit()
        destroy_window()






if __name__ == '__main__':
    import ModificarUsuarioEspecialista
    ModificarUsuarioEspecialista.vp_start_gui()




